name: Deploy Snowflake

on:
  push:
    branches:
      - dev
      - qa
      - main      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 🔹 Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 🔹 Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # 🔹 Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      # 🔹 Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      # 🔹 Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 🔹 Install schemachange
      - name: Install schemachange
        run: pip install schemachange

      # 🔹 Run schemachange (dynamic DB)
      - name: Deploy schema changes
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/dev" ]; then
            DB_NAME=DB_DP_DEV
          elif [ "${GITHUB_REF}" == "refs/heads/qa" ]; then
            DB_NAME=DB_DP_QA
          elif [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            DB_NAME=DB_DP_PROD
          fi
          
          echo "Deploying to $DB_NAME"

          schemachange deploy \
            -f schemachange \
            -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            -u ${{ secrets.SNOWFLAKE_USER }} \
            -r ACCOUNTADMIN \
            -w COMPUTE_WH \
            -d $DB_NAME \
            -s BR_IN \
            --change-history-table $DB_NAME.BR_IN.CHANGE_HISTORY
